<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2wONVP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2wONVP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2wONVP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ2wONVP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ2wONVP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q2wONVP',
    'container.build_id' => '9a266590',
    'container.build_time' => 1635950213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2wONVP');
