<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ZjjUos\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ZjjUos/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ZjjUos.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ZjjUos\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6ZjjUos\App_KernelDevDebugContainer([
    'container.build_hash' => '6ZjjUos',
    'container.build_id' => '1eaf923e',
    'container.build_time' => 1635945989,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ZjjUos');
