<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerANje7RK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerANje7RK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerANje7RK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerANje7RK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerANje7RK\App_KernelDevDebugContainer([
    'container.build_hash' => 'ANje7RK',
    'container.build_id' => 'd6bcd7fd',
    'container.build_time' => 1635944360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerANje7RK');
